<?php
	function military_unit_id_to_name($id) {
		switch ($id) {
			case 1: return "AGAT2";
			case 2: return "Supreme Beings of Leisure";
			case 3: return "GIoria Victis";
			case 4: return "Canadian Armed Forces";
			case 5: return "Ganja";
			case 6: return "LML";
			case 7: return "ZA PRODAJU";
			case 8: return "MACAN";
			case 9: return "Super Fight League";
			case 10: return "Chinese Zodiac";
			case 11: return "OUTSIDER";
			case 12: return "Pak Army";
			case 13: return "Knights of Ni";
			case 14: return "PIRATES";
			case 15: return "101st Airborne Military Unit";
			case 16: return "WFFB";
			case 17: return "Garda Nationala";
			case 18: return "SpartanS";
			case 19: return "Civilian Military Unit";
			case 20: return "La confrerie de la Banane";
			case 21: return "Death Squad";
			case 22: return "Impact";
			case 23: return "Lords";
			case 24: return "Dark Brotherhood";
			case 25: return "Lapinjarven Legioona";
			case 26: return "MARVEL";
			case 27: return "Arbetarmilisen";
			case 28: return "German Company";
			case 29: return "BUSH WACKERS";
			case 30: return "Royal Danish Army";
			case 31: return "EFE Akademi";
			case 32: return "Turk Savas Timi";
			case 33: return "Empire Crusader";
			case 34: return "Fairy Tail";
			case 35: return "Kartel";
			case 36: return "GentleMan";
			case 37: return "Elit Flotta";
			case 38: return "Titani";
			case 39: return "Fuerza Armada Mercenaria";
			case 40: return "TKL";
			case 41: return "Sons of Anarchy Iran branch";
			case 42: return "Bulgarian Peoples Army";
			case 43: return "Principality of Zeon";
			case 44: return "Tides of Fire";
			case 45: return "Indian Garud Commandos";
			case 46: return "Dutch Fighting Machine";
			case 47: return "Weltschmerz";
			case 48: return "Slayers";
			case 49: return "OSBIH";
			case 50: return "Aras";
			case 51: return "merc mu";
			case 52: return "China Org Military";
			case 53: return "aaaaaaaaaaaaaaaaaaaaa";
			case 54: return "Romanian National Security";
			case 55: return "Norway`s MU";
			case 56: return "Vae Victis";
			case 57: return "Chez Maurice";
			case 58: return "Aslantepe";
			case 59: return "Persian Gulf";
			case 60: return "Jeje Boys";
			case 61: return "Thanatos";
			case 62: return "Gloria Victis";
			case 63: return "Alpha Matryoshka Veteran";
			case 64: return "The Immortal Elite";
			case 65: return "LEGIONARS";
			case 66: return "Norway National Army";
			case 67: return "Garda Vojske Srbije";
			case 68: return "Riders On the Storm";
			case 69: return "TROPA";
			case 70: return "Comando Muerte";
			case 71: return "British Army";
			case 72: return "DPS";
			case 73: return "777";
			case 74: return "Legion Etrangere";
			case 75: return "1er Regimiento";
			case 76: return "Bane";
			case 77: return "Akademija Vojske sSrbije";
			case 78: return "Australian Army";
			case 79: return "The Punishers";
			case 80: return "Gwardia Krolewska";
			case 81: return "Civilna Brigada";
			case 82: return "Egoz";
			case 83: return "Imperial Army";
			case 84: return "Swiss Armed Forces";
			case 85: return "SUPER SPECIAL HAPPY MILITARY UNIT";
			case 86: return "Thirsty Hussars";
			case 87: return "Seliing Military Unit";
			case 88: return "Fuerzas Armadas Argentinas II";
			case 89: return "KOPASSUS";
			case 90: return "Gladiators";
			case 91: return "IDF Academy";
			case 92: return "Brigata Partigiana Jovan";
			case 93: return "Brazilian Army II";
			case 94: return "Macedonian Phalanx";
			case 95: return "Indian National Army";
			case 96: return "Marine Commandos II";
			case 97: return "Meme Squad reborn";
			case 98: return "Armee de Terre";
			case 99: return "Dream Team";
			case 100: return "GUNKOSTRAD";
			case 101: return "Alabanas Satara";
			case 102: return "EKIP II";
			case 103: return "I S P";
			case 104: return "SEK AKADEMIJA";
			case 105: return "sePajacyk";
			case 106: return "Fuerzas Armadas Argentinas";
			case 107: return "Peruvian Civil Unit";
			case 108: return "Bad Boys";
			case 109: return "Ejercito de Chile";
			case 110: return "HOS";
			case 111: return "Marine Commandos";
			case 112: return "The Grenadiers";
			case 113: return "ARAS II";
			case 114: return "Fast and Furious";
			case 115: return "Vrazja Divizija";
			case 116: return "Alliance of the Wolves";
			case 117: return "Heroes";
			case 118: return "Srpski Elitni Korpus";
			case 119: return "Squadron Of Light";
			case 120: return "Team of Death V";
			case 121: return "ROK Armed Forces";
			case 122: return "FAE";
			case 123: return "SELLING MU";
			case 124: return "Dark MU";
			case 125: return "SAFE";
			case 126: return "Lietuvos Karines Pajegos 2";
			case 127: return "Vaesir Military unit";
			case 128: return "Gvozdeni puk";
			case 129: return "The Brotherhood of Assassins recruit";
			case 130: return "Territorial Army";
			case 131: return "Slovenska vojska";
			case 132: return "BIRA";
			case 133: return "INCI";
			case 134: return "Brazilian Army";
			case 135: return "Elite Fighters";
			case 136: return "Vojska sSrbije";
			case 137: return "Czyridll";
			case 138: return "The Clergy";
			case 139: return "Onepiece Army";
			case 140: return "Blacksail Pirates";
			case 141: return "IMPERIAL GUARD";
			case 142: return "XxXxXxX";
			case 143: return "Fenrir";
			case 144: return "EDK";
			case 145: return "Banned";
			case 146: return "War Wolf`s";
			case 147: return "Akademija Pirata";
			case 148: return "Thunder Cats";
			case 149: return "123 GARDIJSKA BRIGADA";
			case 150: return "Titani Accademia";
			case 151: return "nevvven";
			case 152: return "Bundeswehr";
			case 153: return "Puolustusvoimat";
			case 154: return "DANS";
			case 155: return "GOE";
			case 156: return "Patruliai";
			case 157: return "Assasins";
			case 158: return "VAS";
			case 159: return "Fighting Rednecks";
			case 160: return "ARMED AMERICA";
			case 161: return "AV Corps";
			case 162: return "Scandinavia";
			case 163: return "New World Order";
			case 164: return "MTO";
			case 165: return "Mobius";
			case 166: return "Bork Bork Bork";
			case 167: return "Hansa Latvia";
			case 168: return "Ireland National Army 2";
			case 169: return "OUTSIDER JR";
			case 170: return "SSG Commandos";
			case 171: return "Comando del Sur";
			case 172: return "Les Cabe el Chori";
			case 173: return "Ponehz";
			case 174: return "MARVEL 2";
			case 175: return "Wanhat Parrat Armeija";
			case 176: return "PRIZNAJEM HRVAT SAM";
			case 177: return "Dogs of War";
			case 178: return "Kolonne";
			case 179: return "UMF";
			case 180: return "Unidad militar Estatal";
			case 181: return "OUTSIDER48 JR";
			case 182: return "Antifa";
			case 183: return "National Taiwan Army";
			case 184: return "iSQUAD";
			case 185: return "PSY Security Alpha";
			case 186: return "Svi Zajedno";
			case 187: return "TEH TROLLYMPIANS";
			case 188: return "Israel Defence Force";
			case 189: return "Army Men Force";
			case 190: return "Shayetet 13";
			case 191: return "Legacy";
			case 192: return "Knights of Cydonia";
			case 193: return "Niezniszczalni";
			case 194: return "No Easy Way Out";
			case 195: return "The Bankai Family";
			case 196: return "Spartans Kids";
			case 197: return "Cyrus the Great";
			case 198: return "EFE";
			case 199: return "KORPS BRIMOB";
			case 200: return "SD6";
			case 201: return "Magyar Legion";
			case 202: return "Questions";
			case 203: return "INSIDER48";
			case 204: return "Pakistan Marines";
			case 205: return "The X Fight";
			case 206: return "Belgian Freedom Unit";
			case 207: return "Bug Stomper";
			case 208: return "FOR SALEEEE";
			case 209: return "Silent Guardians";
			case 210: return "THE FORCES";
			case 211: return "Pixar Animation Studios";
			case 212: return "Shadow Company";
			case 213: return "Anonymous Elite";
			case 214: return "Hvn Org";
			case 215: return "1 GB TIGROVI";
			case 216: return "Haiducii";
			case 217: return "SHADOW";
			case 218: return "People Are Strange";
			case 219: return "Merciless Mercinaries";
			case 220: return "GentleMen";
			case 221: return "CPD Family";
			case 222: return "Defiance";
			case 223: return "Akademia Sil Zbrojnych";
			case 224: return "Manifest Destiny";
			case 225: return "Slovenske legie divizia II";
			case 226: return "Do Not Talk To Me";
			case 227: return "Vojska sCrne Gore";
			case 228: return "Earth`s Special Forces";
			case 229: return "SBoLite";
			case 230: return "Angels of Death";
			case 231: return "Portuguese Minions";
			case 232: return "POLSKA INKWIZYCJA";
			case 233: return "war addicts";
			case 234: return "Mercenary";
			case 235: return "Alpha Matryoshka Elite";
			case 236: return "Heroes of Mexico";
			case 237: return "IPSsI";
			case 238: return "LEGACY";
			case 239: return "Diablo Esquadron Elite";
			case 240: return "Rogue Trooper";
			case 241: return "Italian Bastards";
			case 242: return "AHI";
			case 243: return "Universal";
			case 244: return "Mercenaries of Fortune";
			case 245: return "Raben der Nacht";
			case 246: return "US Air National Guard";
			case 247: return "Central Plains Field Army";
			case 248: return "Elite IRAN Lovers";
			case 249: return "Polskie Sily Zbrojne";
			case 250: return "Ejercito Nacional de Mexico";
			case 251: return "Special Forces Horror";
			case 252: return "Trololo";
			case 253: return "Zombies Army";
			case 254: return "Kontrakan Militer";
			case 255: return "SHANK";
			case 256: return "Macedonian phalanx";
			case 257: return "Delta Squad Australia";
			case 258: return "Magyar Honvedek";
			case 259: return "Hun Horda";
			case 260: return "Made in Slovakia ACADEMY";
			case 261: return "Red Ribbon Army";
			case 262: return "IRISH SPECIAL FORCES";
			case 263: return "Husaria";
			case 264: return "Societas Draconistrarum";
			case 265: return "Pembela Tanah Air";
			case 266: return "Silent Warriors";
			case 267: return "Winter is Coming";
			case 268: return "MUST";
			case 269: return "BH Machine";
			case 270: return "Legionaries";
			case 271: return "Vandals";
			case 272: return "MUUU";
			case 273: return "Bloody freaks";
			case 274: return "For SALE";
			case 275: return "BOPE";
			case 276: return "Zolnierze Bez Granic";
			case 277: return "Lowly Patrolling Kappa";
			case 278: return "VoC";
			case 279: return "PaRs Military";
			case 280: return "US Army";
			case 281: return "ROTSE";
			case 282: return "Swedish Armed Forces";
			case 283: return "SNIPER ELITE";
			case 284: return "S A U L I A I";
			case 285: return "Whatever I Love Indonesia";
			case 286: return "ELITE";
			case 287: return "Vukovi";
			case 288: return "The Zombie Horde";
			case 289: return "8th Squad";
			case 290: return "RRP";
			case 291: return "Freedom Fighters";
			case 292: return "Alpha Platoon";
			case 293: return "Team of Death";
			case 294: return "The Red Army";
			case 295: return "S H I E L D";
			case 296: return "007";
			case 297: return "Anonymous Jr";
			case 298: return "Unidade Militar Armada Celeste";
			case 299: return "Ejercito Elite Mexicano";
			case 300: return "TNsI";
			case 301: return "Patriotai";
			case 302: return "1896";
			case 303: return "Armada Peruana";
			case 304: return "The Gentlemen";
			case 305: return "On sale";
			case 306: return "Kuvayi Milliye";
			case 307: return "Titans";
			case 308: return "VOJIN";
			case 309: return "The Avengers";
			case 310: return "Dywizjon Jazdy Ochotniczej";
			case 311: return "Hang Loose";
			case 312: return "Slovenske legie divizia I";
			case 313: return "ORZEU JAZGULKA";
			case 314: return "The Red Devils";
			case 315: return "La Comu de secura";
			case 316: return "Iranian Elite Forces";
			case 317: return "Royal";
			case 318: return "Freedom";
			case 319: return "Brasilian Avengers";
			case 320: return "Engineers";
			case 321: return "Srpski Rezervisti";
			case 322: return "The Resistance";
			case 323: return "Greece Russia Serbia";
			case 324: return "MACEDONIAN HELLENIC ARMY";
			case 325: return "Serpiente";
			case 326: return "EKIP l";
			case 327: return "Punakaarti";
			case 328: return "Iran National Army";
			case 329: return "IMMORTAL GUARD";
			case 330: return "The Unit 55";
			case 331: return "DRAKE";
			case 332: return "Jobnikim";
			case 333: return "XERS";
			case 334: return "Vikings";
			case 335: return "The Royal Marines";
			case 336: return "Jedi Academy";
			case 337: return "UTOPIA ELIT";
			case 338: return "Old Legion";
			case 339: return "SHIELD";
			case 340: return "Blood BrotherHood";
			case 341: return "Englisc Fyrd";
			case 342: return "Angkatan Tentera Malaysia";
			case 343: return "The Savages2";
			case 344: return "Dussel Force";
			case 345: return "FREE ENTER";
			case 346: return "ENJOY";
			case 347: return "White Legion";
			case 348: return "Four Horsemen";
			case 349: return "Pew Pew";
			case 350: return "JFF";
			case 351: return "GHurka Org";
			case 352: return "Commissione Interministeriale Tecnica della Difesa Civile";
			case 353: return "ciumpackiukai";
			case 354: return "naors unit";
			case 355: return "Akatsuki Armed Forced";
			case 356: return "BLADE";
			case 357: return "The GodFather";
			case 358: return "GOODBYE ESIM";
			case 359: return "Bajen Corps";
			case 360: return "Blood Hunters";
			case 361: return "TelorGaruda";
			case 362: return "Iranian National Unit";
			case 363: return "Les Bleus de France";
			case 364: return "The Bazaar";
			case 365: return "AKINCILAR";
			case 366: return "Oligarchy";
			case 367: return "Knights Of The Round";
			case 368: return "Pasukan Bayangan";
			case 369: return "HRVATSKA RATNA MORNARICA";
			case 370: return "mushroom elves";
			case 371: return "Praetorian Guard";
			case 372: return "Just For Fun";
			case 373: return "Taiwan Miruki Force";
			case 374: return "Black Pearl";
			case 375: return "Sayeret Matkal";
			case 376: return "BG_ARMY";
			case 377: return "AleXandar `s Unit";
			case 378: return "Leones del Sur";
			case 379: return "League of Gentlemans";
			case 380: return "CPD Junior";
			case 381: return "legionarii";
			case 382: return "The Screaming Eagles";
			case 383: return "Gokturk Ordusu";
			case 384: return "Patriots";
			case 385: return "LTK";
			case 386: return "Domacini";
			case 387: return "Ravenwood";
			case 388: return "Patriotyczna Grupa Uderzeniowa";
			case 389: return "Garda Kombetare";
			case 390: return "Slovak Special Legion";
			case 391: return "Nereids";
			case 392: return "The Two Clickers";
			case 393: return "MERCENARY";
			case 394: return "Laskar Ngapak";
			case 395: return "GO Wyszkow";
			case 396: return "eBebe MU";
			case 397: return "OWLS";
			case 398: return "21st infantry division";
			case 399: return "GAMA";
			case 400: return "Pagourades";
			case 401: return "Family";
			case 402: return "Cat Company";
			case 403: return "SS Communist Marxisme";
			case 404: return "Islamistinen Erikoiskomppania";
			case 405: return "DEADSQUAD";
			case 406: return "UK Training camp";
			case 407: return "GVOZDENI PUK akademija";
			case 408: return "Special MU";
			case 409: return "Walking Dead Army";
			case 410: return "Golden Party Military Unit";
			case 411: return "Turcos";
			case 412: return "Nordic battlegroup";
			case 413: return "Gullivers";
			case 414: return "ROC KOKA";
			case 415: return "Njabz";
			case 416: return "LEGION DE HONOR";
			case 417: return "Ura Uruha";
			case 418: return "Blind Guardians";
			case 419: return "Legiony Polskie";
			case 420: return "Carebears";
			case 421: return "Baltieji vilkai";
			case 422: return "SERE";
			case 423: return "Slovanska Jednota";
			case 424: return "Estonian army";
			case 425: return "Sirene Merah";
			case 426: return "Czarne Owieczki Black Sheep";
			case 427: return "Srpski strelci";
			case 428: return "zero military";
			case 429: return "Newbies Elite Force";
			case 430: return "BIM 5";
			case 431: return "Sekarep Ndas moDe";
			case 432: return "Brotherhood Unity";
			case 433: return "UNIT 69";
			case 434: return "Bosnjacki NEO";
			case 435: return "Drunken Sailors";
			case 436: return "Austrian Liberation Army";
			case 437: return "red army";
			case 438: return "Like a Sir MU";
			case 439: return "3er Regimiento";
			case 440: return "Spix Unit";
			case 441: return "Veterans";
			case 442: return "THE RED ARMY";
			case 443: return "Samogitians";
			case 444: return "WTS";
			case 445: return "Italian Force";
			case 446: return "Nationalisme";
			case 447: return "SHIELD international";
			case 448: return "EnGiNeeRs";
			case 449: return "Greece International";
			case 450: return "avaye pedar";
			case 451: return "IRANIAN SOLDIER";
			case 452: return "Clueless";
			case 453: return "Anime Special Force";
			case 454: return "Elite Eagles";
			case 455: return "Military";
			case 456: return "FOR SALE MU";
			case 457: return "Nuclear";
			case 458: return "TBH";
			case 459: return "Elite Tiger Guards";
			case 460: return "BULGARIA";
			case 461: return "ITC Security";
			case 462: return "Phalanx";
			case 463: return "Death Eater";
			case 464: return "Romanian Elite Fighters";
			case 465: return "Vitesse";
			case 466: return "DELIJE SEVER";
			case 467: return "Indian Defense Academy";
			case 468: return "Na Pohybel Skurczysynom";
			case 469: return "Kuu";
			case 470: return "GOLGE";
			case 471: return "BANG BANG BANG";
			case 472: return "BG Batangan Legion";
			case 473: return "HELLENIC AIR FORCE";
			case 474: return "Civilna Brigada BiH";
			case 475: return "HIGH 5";
			case 476: return "Brazilian Army Academy";
			case 477: return "SELL FOR 35GOLDS";
			case 478: return "SAKARYA";
			case 479: return "Canisius Army Force";
			case 480: return "Alliance of the WoIves";
			case 481: return "HUN aljaElit UNIT";
			case 482: return "Marine Recon Unit";
			case 483: return "Jugoslavija";
			case 484: return "Lycan Troops";
			case 485: return "Immortal Guard";
			case 486: return "SHINING PATHS";
			case 487: return "Vortex";
			case 488: return "Slovenija";
			case 489: return "Romanian Crowned Dragons";
			case 490: return "Spartiatiki Agwgi";
			case 491: return "National Taiwan Marine Corps";
			case 492: return "Weltschmerz II";
			case 493: return "Demons";
			case 494: return "Lavovi";
			case 495: return "TSK";
			case 496: return "Kompanie Alpha";
			case 497: return "Bundesheer";
			case 498: return "Rapid Action Millitia";
			case 499: return "Revolucionarios del Parque";
			case 500: return "Elementz Unit";
			case 501: return "Nocna Zmiana";
			case 502: return "Przyczajone Tygrysy";
			case 503: return "Pontificia Cohors Helvetica";
			case 504: return "eLiechtenstein";
			case 505: return "Forces Speciales Francaises";
			case 506: return "VasilijausCepajavoBurys";
			case 507: return "AHEGAO DESU";
			case 508: return "Rogue Squadron";
			case 509: return "SOS";
			case 510: return "Portuguese Minions Kids";
			case 511: return "Mine";
			case 512: return "19701980";
			case 513: return "DRACONES";
			case 514: return "Turk Ordusu";
			case 515: return "Regular Army";
			case 516: return "DEMONS";
			case 517: return "Sicarii";
			case 518: return "Cutie Mark Crusaders";
			case 519: return "Turkfire";
			case 520: return "Anonymous Legion";
			case 521: return "Crash";
			case 522: return "marsovci";
			case 523: return "Goal";
			case 524: return "Unidade Militar Portuguesa";
			case 525: return "R K O";
			case 526: return "Homura Force";
			case 527: return "Komando Malaysia";
			case 528: return "Fun Only Team";
			case 529: return "Anti_Legionari";
			case 530: return "Star Fox";
			case 531: return "SUGIUC";
			case 532: return "MERCENARY Devils Army";
			case 533: return "Rajnikanth Army";
			case 534: return "Black Panthers";
			case 535: return "GHOST";
			case 536: return "Global Soldiers";
			case 537: return "DickSquad";
			case 538: return "Ozbrojene sily SR Akademia";
			case 539: return "royal guard of iran";
			case 540: return "BRIMOB";
			case 541: return "BNS Warriors";
			case 542: return "The Front of Armament";
			case 543: return "Hungarian Elit Unit";
			case 544: return "Polish Private Army";
			case 545: return "Los Turcos";
			case 546: return "BAY";
			case 547: return "FARC UP";
			case 548: return "Srpska narodna armija";
			case 549: return "BlackBird";
			case 550: return "Business Smurfs";
			case 551: return "FireTeam";
			case 552: return "AIRFORCE";
			case 553: return "4 GB PAUCI";
			case 554: return "HGG";
			case 555: return "AOM";
			case 556: return "GoldBull";
			case 557: return "Ekki Mukk";
			case 558: return "Pak Air Force";
			case 559: return "SEKS";
			case 560: return "Tut Wuri Handayani";
			case 561: return "Grave Digger Clan";
			case 562: return "Super Happy Fun Time Cow";
			case 563: return "Canuckistani Extremists";
			case 564: return "Order of Assassins";
			case 565: return "Smoking Kills";
			case 566: return "Myrmidones";
			case 567: return "White Coast Rebels";
			case 568: return "Perkanus";
			case 569: return "BNK Dragons";
			case 570: return "Unknown Soldiers of Imam Mahdi";
			case 571: return "Division Azul";
			case 572: return "Diamond Sword";
			case 573: return "KaMiKaZe";
			case 574: return "HULK";
			case 575: return "l S P";
			case 576: return "Vanatorii de campie";
			case 577: return "Milorg";
			case 578: return "Svenska Klubben";
			case 579: return "The Expendables";
			case 580: return "Anjos da Guerra";
			case 581: return "Terere Squad";
			case 582: return "Spurdot";
			case 583: return "For sell";
			case 584: return "Toxy MU";
			case 585: return "Marcenary";
			case 586: return "PERSIA";
			case 587: return "Valar Morghulis";
			case 588: return "Colombia Elite";
			case 589: return "Two Man Army";
			case 590: return "Salvation Army";
			case 591: return "Israel Mu";
			case 592: return "Irish Army";
			case 593: return "Royal Greek Armed Forces";
			case 594: return "Nederlandse Twentse Strijdmacht";
			case 595: return "Polish Army";
			case 596: return "A Damage MU";
			case 597: return "UNIT";
			case 598: return "Vapaa";
			case 599: return "MU lkuka G";
			case 600: return "Catch XXII";
			case 601: return "Ariyaii";
			case 602: return "FUN";
			case 603: return "RED ARMY";
			case 604: return "3 Gardijska Brigada Kune";
			case 605: return "POST";
			case 606: return "FIRE";
			case 607: return "Military Unit";
			case 608: return "Ltd Academy";
			case 609: return "J E D I N I C A";
			case 610: return "Balkan ExpreS";
			case 611: return "eGoz";
			case 612: return "Cvajklikers Slovenija";
			case 613: return "Online Military Guerilla";
			case 614: return "splinanteros unit";
			case 615: return "Gladiatori Italiani";
			case 616: return "BH Hunters";
			case 617: return "KMS48";
			case 618: return "SMURFS";
			case 619: return "Egypt Elite";
			case 620: return "HEADSHOT";
			case 621: return "Kraljeva Garda";
			case 622: return "Order of Kshatriyas";
			case 623: return "Sprdex United";
			case 624: return "Soldiers Without Borders";
			case 625: return "Pasukan Kampret";
			case 626: return "Ozbrojene sily SR";
			case 627: return "staabs";
			case 628: return "Korps Mariniers";
			case 629: return "SAO";
			case 630: return "Mindaugo MU";
			case 631: return "United Forces of Belgium";
			case 632: return "CAT";
			case 633: return "Srb Fighters";
			case 634: return "AMiGO";
			case 635: return "Elfen Lied";
			case 636: return "Tmavy Anjel";
			case 637: return "AxE";
			case 638: return "Nights Watch";
			case 639: return "Ventic";
			case 640: return "EUPHORIA";
			case 641: return "Vitezovi slavonske ravnice";
			case 642: return "Chinese People Liberation Army";
			case 643: return "Mercenary Army";
			case 644: return "atWar";
			case 645: return "Heppikevonen";
			case 646: return "Anonymous Team";
			case 647: return "mirmidones";
			case 648: return "playbook";
			case 649: return "BABE";
			case 650: return "Seohyuns Peacekeepers";
			case 651: return "_GPS_";
			case 652: return "Pedro MU";
			case 653: return "PaiN";
			case 654: return "27 Panzer";
			case 655: return "admin mu";
			case 656: return "DarkDragons";
			case 657: return "Ukraine Black Guard";
			case 658: return "Pirate Ninjas Clan";
			case 659: return "nevvven Jr";
			case 660: return "Atoms Family";
			case 661: return "Equilibrium";
			case 662: return "HUE HUE HUE ARMY";
			case 663: return "Independent Pakistan";
			case 664: return "The Sickest Squad";
			case 665: return "UTOPIA";
			case 666: return "Manus Dei";
			case 667: return "Sayeret 2";
			case 668: return "The Army of Worldwide";
			case 669: return "No mercy";
			case 670: return "Brazilian Forces";
			case 671: return "Unamed";
			case 672: return "Osmanli Ordusu";
			case 673: return "Gladio";
			case 674: return "Private Military";
			case 675: return "Red crvenog zmaja";
			case 676: return "The US Militia";
			case 677: return "American Liberation Force";
			case 678: return "SK MU";
			case 679: return "Ckt Army";
			case 680: return "Iz principa o7";
			case 681: return "PAK Armed Force";
			case 682: return "No Retreat No Surrender";
			case 683: return "GooDKaT Force";
			case 684: return "Muna";
			case 685: return "MU do Augusto9";
			case 686: return "Romanian Defenders";
			case 687: return "POLReSIM";
			case 688: return "The AniMaLs";
			case 689: return "RAIDER 700";
			case 690: return "Baltic Corps";
			case 691: return "MACEDONIAN NATIONAL GUARD CRUSADERS";
			case 692: return "Assassins International Team";
			case 693: return "Hrvatski domobrani";
			case 694: return "Frontline Fighters";
			case 695: return "Ujarana Armia";
			case 696: return "Los Liberalos y Los Lobistos";
			case 697: return "el bravos";
			case 698: return "INF Security Services";
			case 699: return "UFO";
			case 700: return "BeYonD";
			case 701: return "Estonia";
			case 702: return "Cosa Nostra";
			case 703: return "GUERILLA";
			case 704: return "PaRs aRmY";
			case 705: return "ZaytunG";
			case 706: return "estel";
			case 707: return "ALPHA";
			case 708: return "INDIAN LAST WARIORS";
			case 709: return "Private Warehouse";
			case 710: return "Sons of Guns";
			case 711: return "International Volunteer Army";
			case 712: return "Just 4 Fun";
			case 713: return "BlackDevil";
			case 714: return "Whiskey Company";
			case 715: return "KOSTRAD";
			case 716: return "WOLFPACK";
			case 717: return "Skull Crushers";
			case 718: return "Bombay Army";
			case 719: return "Virtuti Militari";
			case 720: return "mu mu mu mu";
			case 721: return "KSI";
			case 722: return "Lions";
			case 723: return "Royal Family";
			case 724: return "EL MESSIAS";
			case 725: return "Nazgul";
			case 726: return "All 4 One";
			case 727: return "Illyrians Academy";
			case 728: return "Gyilkos muslinca";
			case 729: return "nigThMare mercenry";
			case 730: return "roohhhh";
			case 731: return "TLoU";
			case 732: return "The Bass Military Unit";
			case 733: return "FOR SALE";
			case 734: return "National Taiwan 6th Army Corps";
			case 735: return "Absolute Zero";
			case 736: return "MBS";
			case 737: return "test military unit";
			case 738: return "Hungarian Royal Army";
			case 739: return "Bojna za specijalna djelovanja";
			case 740: return "pohjanmaa";
			case 741: return "Os Solitarios";
			case 742: return "Babu Saiyans";
			case 743: return "Lone Wolf";
			case 744: return "Peacetime Training Organization";
			case 745: return "Makedonska Nacionalna Garda Akademija";
			case 746: return "BCh";
			case 747: return "salami";
			case 748: return "Garde imperiale";
			case 749: return "Spac Sozluk";
			case 750: return "United Europe";
			case 751: return "Black Water Recruits";
			case 752: return "Ball So Hard";
			case 753: return "Presiden Unit";
			case 754: return "The Assassins for sale";
			case 755: return "EKO Cobra";
			case 756: return "Daltoni";
			case 757: return "Base Beta";
			case 758: return "Nanban Ronins";
			case 759: return "Devastating Aristocrats";
			case 760: return "Primera Rulez";
			case 761: return "ElitEZ";
			case 762: return "I S S";
			case 763: return "MAFIA";
			case 764: return "GODLIKE";
			case 765: return "GUERRA CONTINUA";
			case 766: return "2clickers";
			case 767: return "W I L D S Q U A D";
			case 768: return "For Sale 85 Gold";
			case 769: return "boboN1";
			case 770: return "Mercanary Noobs";
			case 771: return "YNWA";
			case 772: return "SEXY ARMY";
			case 773: return "Blaze";
			case 774: return "Hostile";
			case 775: return "DireWolves";
			case 776: return "YUZORA";
			case 777: return "Invincible Troop";
			case 778: return "Reunion";
			case 779: return "Divisione ARIETE";
			case 780: return "Armija na Republika Makedonija";
			case 781: return "Marele Lup Alb";
			case 782: return "Solitude";
			case 783: return "Uber Najjaci Najzakon CRO Team MU HRVATSKA Vojna jedinica";
			case 784: return "Nordic Mu Masters";
			case 785: return "Ouch";
			case 786: return "Gloria_Victis";
			case 787: return "GoldMU";
			case 788: return "Military unit reserve Bank COOPERATIVE 2";
			case 789: return "Military unit reserve Bank COOPERATIVE";
			case 790: return "28 Jun";
			case 791: return "Rongyos Garda";
			case 792: return "Lost Legion";
			case 793: return "Silly Warriors";
			case 794: return "Philippine Special Action Force";
			case 795: return "WGAF";
			case 796: return "Army of Heaven";
			case 797: return "Freedom fighters";
			case 798: return "Akademija J E D I N I C E";
			case 799: return "SAJ";
			case 800: return "lazy stars";
			case 801: return "Batalyon Cakra Nanggala";
			case 802: return "Partizanski odred";
			case 803: return "National Taiwan 8th Army Corps";
			case 804: return "pokemonking";
			case 805: return "ocak";
			case 806: return "xxxxxxx";
			case 807: return "TURAN ORDUSU";
			case 808: return "Sociedade dos Herois mortos";
			case 809: return "111 GB Zmajevi";
			case 810: return "Spetsnaz Regiment";
			case 811: return "Last Military Unit";
			case 812: return "SRB_ TIGROVI";
			case 813: return "Decepticons";
			case 814: return "Albanian Special TeaM";
			case 815: return "Outlaws";
			case 816: return "RENEA";
			case 817: return "OMM";
			case 818: return "Bozkurtlar";
			case 819: return "BND";
			case 820: return "SiIent Guardians";
			case 821: return "UCK";
			case 822: return "Makedonskite Templari";
			case 823: return "Soldados del Sur";
			case 824: return "Otaku Bytes";
			case 825: return "Canadian Military Unit";
			case 826: return "KIZIL ORDU";
			case 827: return "Foreign Legion";
			case 828: return "Chartwin Legion";
			case 829: return "Regjimenti Komando";
			case 830: return "Mente";
			case 831: return "EYR";
			case 832: return "t65";
			case 833: return "Teskilati Mahsusa";
			case 834: return "CELL StriKE";
			case 835: return "PaRs Military BrOtHeRhoOd";
			case 836: return "Islamic republic of iran army";
			case 837: return "Saule";
			case 838: return "Silesian Independence Army";
			case 839: return "AssassinS";
			case 840: return "Templari";
			case 841: return "North Ocean";
			case 842: return "PLA_Tiger Even";
			case 843: return "Wolf";
			case 844: return "Taurunum Strike Force";
			case 845: return "XxX Movies";
			case 846: return "669 Force";
			case 847: return "Ghosts";
			case 848: return "FOOR SALEE";
			case 849: return "Apex Predators";
			case 850: return "Orlovi rano lete";
			case 851: return "Teutons";
			case 852: return "7 gardijska brigada PUME";
			case 853: return "Ozel Harekat Timi";
			case 854: return "OTTOMAN ARMY";
			case 855: return "Gelezinis Vilkas";
			case 856: return "Absolute Swag";
			case 857: return "7 GB Pume";
			case 858: return "slardar";
			case 859: return "Rewind Military Unit";
			case 860: return "One Man Army";
			case 861: return "Revolutionary army";
			case 862: return "KDS Reserve Corps";
			case 863: return "Srpska elitna jedinica";
			case 864: return "Just The Game";
			case 865: return "BARABE VLADAJU SVETOM";
			case 866: return "Little Busters";
			case 867: return "Chinese Red Army";
			case 868: return "Inner Circle";
			case 869: return "MORE DOTS";
			case 870: return "Rebel Alliance";
			case 871: return "Bombers";
			case 872: return "Knindze Krajisnici";
			case 873: return "Balkanska legija";
			case 874: return "Puponautai";
			case 875: return "CRNI VITEZI RAVNE SLAVONIJE";
			case 876: return "BOPE Tropa De Elite";
			case 877: return "AP Military";
			case 878: return "baarreie naghola";
			case 879: return "International Military Unit";
			case 880: return "Brigata Italiana";
			case 881: return "Dywizjon 303";
			case 882: return "Task Force 141";
			case 883: return "Squadron Of Light junior";
			case 884: return "Exercito Brasileiro Independente";
			case 885: return "More damage";
			case 886: return "team boobs";
			case 887: return "Baby Oligarchs";
			case 888: return "Srpska vojska";
			case 889: return "Szturmowcy";
			case 890: return "SHARKS";
			case 891: return "Volkof Industries Guard";
			case 892: return "Forces Speciales Francaises Kaunas";
			case 893: return "Batalhao de Infantaria";
			case 894: return "Grom";
			case 895: return "Szwadron";
			case 896: return "KDS Army";
			case 897: return "OMNIA";
			case 898: return "ELITE ARCHERS";
			case 899: return "bilibili will";
			case 900: return "Passing Shot Fired";
			case 901: return "Welcome_in_Shadow";
			case 902: return "Wings of Glory";
			case 903: return "Le3k";
			case 904: return "SLOTHS";
			case 905: return "Pluton";
			case 906: return "AFoS";
			case 907: return "Secura Golden Ways";
			case 908: return "super army";
			case 909: return "Gloria Victis 2";
			case 910: return "Armed Businessman";
			case 911: return "Great Dane Unit";
			case 912: return "yggdra union";
			case 913: return "For the Bonus";
			case 914: return "Nenugalimieji";
			case 915: return "Akademija Srpski Tigrovi";
			case 916: return "MrHeksas MU";
			case 917: return "Spartaa";
			case 918: return "ARIAN";
			case 919: return "Freedom Fighterz";
			case 920: return "Wardens";
			case 921: return "Forcat Ushtarake";
			case 922: return "Atomarer Endschlag";
			case 923: return "TIGER ARMY";
			case 924: return "PLA_Air Force";
			case 925: return "ARGONAUTES";
			case 926: return "WRS Military Unit";
			case 927: return "Glory";
			case 928: return "SSS";
			case 929: return "Battle Beast";
			case 930: return "BlackWatch";
			case 931: return "Macedonians";
			case 932: return "DIAS";
			case 933: return "Black Armoured Force";
			case 934: return "Tipo MU";
			case 935: return "ALFA";
			case 936: return "Albanian Miliatary";
			case 937: return "fresh man party";
			case 938: return "Trip Of the World";
			case 939: return "Farvahar";
			case 940: return "Svolta Italiana";
			case 941: return "Crvene beretke";
			case 942: return "SERBIAN LEGION";
			case 943: return "Praetorians";
			case 944: return "Rohirrim";
			case 945: return "Gooners";
			case 946: return "V M R O";
			case 947: return "EADS";
			case 948: return "British Battalion";
			case 949: return "makeinu";
			case 950: return "Crna Legija";
			case 951: return "Kara Sancak";
			case 952: return "Cheeese 2d";
			case 953: return "HOS Devetnaesta bojna";
			case 954: return "Wings cut off evil";
			case 955: return "Crann Bethadh";
			case 956: return "Friendly Company";
			case 957: return "TNT";
			case 958: return "armata rosie";
			case 959: return "Fogfighter MU";
			case 960: return "PLA_TE reserve duty";
			case 961: return "MORTAL HAWKS";
			case 962: return "PanzerGranadieren";
			case 963: return "Aura";
			case 964: return "For Sale";
			case 965: return "Glory Romania";
			case 966: return "Black Legion";
			case 967: return "Macedonian Army";
			case 968: return "1st GM_LTU";
			case 969: return "SFRY";
			case 970: return "hydra";
			case 971: return "Ghosts 2";
			case 972: return "Srpski Gardisti";
			case 973: return "Guerilla";
			case 974: return "MOON CRAZY HOSPITAL";
			case 975: return "LATSIDA CRETE";
			case 976: return "STaAS";
			case 977: return "Zandarmerija Srbije";
			case 978: return "Polar Bear Army";
			case 979: return "551";
			case 980: return "Grupa TNT";
			case 981: return "ROC Force";
			case 982: return "Vilkas";
			case 983: return "Ravnogorski Pokret Cetnika";
			case 984: return "Newbies";
			case 985: return "Para Commandos";
			case 986: return "Tree Diagram";
			case 987: return "Subterranean Animism";
			case 988: return "Mobarezine Iran";
			case 989: return "Assasins GB";
			case 990: return "PECINTA TOGE";
			case 991: return "UCCU";
			case 992: return "LITHUANIANS";
			case 993: return "USA Novice MU";
			case 994: return "JOKER";
			case 995: return "Armija Republike Bosne i Hercegovine";
			case 996: return "Qc Fighters";
			case 997: return "Fast";
			case 998: return "Civilna Brigada Hrvatske";
			case 999: return "pleshti mu";
			case 1000: return "KerKer MU";
			case 1001: return "No Shame";
			case 1002: return "Spiochy";
			case 1003: return "Guns Guns";
			case 1004: return "Born Neo";
			case 1005: return "18 Mercenary Group";
			case 1006: return "RAF Royal Army Force";
			case 1007: return "Brdjani";
			case 1008: return "Bulgarian MU";
			case 1009: return "Partido Democrata Progresista";
			case 1010: return "AVATARI";
			case 1011: return "GNR";
			case 1012: return "BalkanDefenceForce";
			case 1013: return "KOPASSUS sINDONESIA";
			case 1014: return "latsabb";
			case 1015: return "Brigada 1942";
			case 1016: return "Ninja MU";
			case 1017: return "Mazowsze";
			case 1018: return "Secura Cross";
			case 1019: return "Borci za pravdu";
			case 1020: return "Fuerza de Defensa de Venezuela";
			case 1021: return "FightForHonor";
			case 1022: return "Ghosts3";
			case 1023: return "Hunters Association";
			case 1024: return "TMNT";
			case 1025: return "Forcas Especiais";
			case 1026: return "Bulgaria";
			case 1027: return "Liberators";
			case 1028: return "Guardia Cacique Guaicaipuro";
			case 1029: return "Indonesian ZAFT";
			case 1030: return "Armada Argentina";
			case 1031: return "Fuerza Armada Independiente";
			case 1032: return "Soldati Fratello";
			case 1033: return "NiesiemyDlaWasBombe";
			case 1034: return "PLI Military";
			case 1035: return "Amanvienalga";
			case 1036: return "Ruch Narodowy";
			case 1037: return "TESKILAT";
			case 1038: return "FREEDOM FIGHTERS";
			case 1039: return "Zvijeri";
			case 1040: return "Ejercito Imperio";
			case 1041: return "Comando Delta";
			case 1042: return "Altiszti Akademia";
			case 1043: return "TURAN TUGAYI";
			case 1044: return "BITCH PLEASE";
			case 1045: return "Anonymous Army";
			case 1046: return "FANV";
			case 1047: return "09 Division Tiger flag Army";
			case 1048: return "Dragon Power";
			case 1049: return "Milizia Volontaria per la Sicurezza Nazionale";
			case 1050: return "Serbian killers";
			case 1051: return "UK Fights Back";
			case 1052: return "STAR";
			case 1053: return "Srpska Legija";
			case 1054: return "WIZARDS";
			case 1055: return "Ejercito Sin Fronteras";
			case 1056: return "Venezuelan Army";
			case 1057: return "Friends Bank";
			case 1058: return "iron maiden";
			case 1059: return "SEBIN";
			case 1060: return "Space travel and colonization group";
			case 1061: return "The Lethals";
			case 1062: return "Red Army Military Unit";
			case 1063: return "Zmajevi BiH";
			case 1064: return "Taiwan Glorious Army";
			case 1065: return "Smartt Fight";
			case 1066: return "BHF";
			case 1067: return "Raider Batalion";
			case 1068: return "The Mediterranean Forces";
			case 1069: return "RANGER";
			case 1070: return "5th SFR";
			case 1071: return "Century Warlord";
			case 1072: return "CHINA Long Unit";
			case 1073: return "Plavi Grom";
			case 1074: return "BSP Wolwes";
			case 1075: return "The Jokermans";
			case 1076: return "TCBC";
			case 1077: return "Pirate Storm Troopers";
			case 1078: return "Typous";
			case 1079: return "Blackwater";
			case 1080: return "Socrates";
			case 1081: return "KAGERO DAZE";
			case 1082: return "Garda Roxa";
			case 1083: return "SEC";
			case 1084: return "Securaku Force";
			case 1085: return "JaegerKorpset";
			case 1086: return "VSBiH";
			case 1087: return "IMF";
			case 1088: return "League of Legends";
			case 1089: return "French Patriots";
			case 1090: return "TGA";
			case 1091: return "Tigrovi";
			case 1092: return "Armada Nacional de Mexico";
			case 1093: return "persian warriors";
			case 1094: return "ULV";
			case 1095: return "prototype";
			case 1096: return "soy sauce";
			case 1097: return "HVO";
			case 1098: return "MiM Mu";
			case 1099: return "Gladiators_Cro_";
			case 1100: return "Mikolow Rangers";
			case 1101: return "soldier of Owari Legion";
			case 1102: return "Night Watch";
			case 1103: return "KGB";
			default: return "";
		}
	}
?>